[project]
name = "contextmaker"
version = "0.1.0"
description = "A simple context‐builder and converter toolkit"
authors = [
  { name = "Chadi Ait Ekioui", email = "chadiaitek2004@gmail.com" },
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
  "Programming Language :: Python :: 3"
]

[tool.setuptools.packages.find]
where = ["src"]